[[language]]
name = "nix"
formatter.command = "nixpkgs-fmt"
language-servers = ["nixd"]
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.files]
watcher = "server"

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "codebook"]

[[language]]
name = "java"
language-servers = ["jdtls"]
formatter.command = "google-java-format"
formatter.args = ["-"]
auto-format = true

